spring:
  application:
    name: opendata-crud
  datasource:
    url: jdbc:mariadb://localhost:3306/polytech
    username: bal
    password: YmVFwKjXLZdMfC7WJB2Dys
    driver-class-name: org.mariadb.jdbc.Driver